# Generated by Django 2.0.6 on 2020-09-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serializersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='pic',
            field=models.ImageField(default='pic/5acd2ac3d6b860ea7708eff4abe84397.jpg', upload_to='pic'),
        ),
    ]
